import React, { lazy } from 'react';
import { LoadingComponent } from '../components/general/components/loading-view.component';
import { IRoute } from './interface';

export const routes: IRoute[] = [
    {
        path: '/',
        exact: true,
        redirect: '/home',
        fallback: <LoadingComponent />,
    },
    {
        path: '/home',
        component: lazy(() => import('../components/home/home.screen')),
        exact: false,
        private: false,
        fallback: <LoadingComponent />,
    },
    {
        path: '/account',
        component: lazy(() => import('../components/account/screens/account.screen')),
        exact: false,
        private: false,
        fallback: <LoadingComponent />,
    },
    {
        path: '/new',
        exact: true,
        redirect: '/new/all',
        fallback: <LoadingComponent />,
    },
    {
        path: '/new/:id',
        component: lazy(() => import('../components/product-list/screens/novelty-product-list.screen')),
        exact: false,
        private: false,
        fallback: <LoadingComponent />,
    },
    {
        path: '/catalog',
        exact: true,
        redirect: '/catalog/all',
        fallback: <LoadingComponent />,
    },
    {
        path: '/catalog/:id',
        component: lazy(() => import('../components/product-list/screens/product-list.screen')),
        exact: false,
        private: false,
        fallback: <LoadingComponent />,
    },
    {
        path: '/order-confirmation',
        component: lazy(() => import('../components/checkout/screens/order-confirmation.screen')),
        exact: false,
        private: false,
        fallback: <LoadingComponent />,
    },
    {
        path: '/basket',
        component: lazy(() => import('../components/checkout/screens/basket.screen')),
        exact: false,
        private: false,
        fallback: <LoadingComponent />,
    },
    {
        path: '/contacts',
        component: lazy(() => import('../components/contacts/contacts.screen')),
        exact: false,
        private: false,
        fallback: <LoadingComponent />,
    },
    {
        path: '/delivery',
        component: lazy(() => import('../components/delivery/delivery.screen')),
        exact: false,
        private: false,
        fallback: <LoadingComponent />,
    },
    {
        path: '/check-order',
        component: lazy(() => import('../components/order/check-order.screen')),
        exact: false,
        private: false,
        fallback: <LoadingComponent />,
    },
    {
        path: '/product-details/:id',
        component: lazy(() => import('../components/product-details/product-details.screen')),
        exact: false,
        private: false,
        fallback: <LoadingComponent />,
    },
    {
        path: '/search',
        component: lazy(() => import('../components/product-list/screens/search-product-list.screen')),
        exact: false,
        private: false,
        fallback: <LoadingComponent />,
    },
    {
        path: '/promotion/:id',
        component: lazy(() => import('../components/promotions/screens/promotion-details.screen')),
        exact: false,
        private: false,
        fallback: <LoadingComponent />,
    },
    {
        path: '/promotions',
        component: lazy(() => import('../components/promotions/screens/promotion-list.screen')),
        exact: true,
        private: false,
        fallback: <LoadingComponent />,
    },
    {
        path: '/compare',
        component: lazy(() => import('../components/compare-products/compare-products.screen')),
        exact: true,
        private: false,
        fallback: <LoadingComponent />,
    },
];
